language: python
sudo: false
python: 2.7
cache:
  pip: true
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N -q
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: 
  - bin/coverage run bin/test
  - bin/code-analysis
after_success:
  - pip install -q coveralls python-coveralls==2.5.0 coverage==3.7.1
  - coveralls
