language: python
sudo: false
python: 2.7
env:
  matrix:
    - PLONE_VERSION=4.3
    - PLONE_VERSION=5.0
    - PLONE_VERSION=5.1
cache:
  pip: true
  directories:
    - buildout-cache/eggs       # see buildout-cache.cfg
    - buildout-cache/downloads  # see buildout-cache.cfg
install:
  - sed -ie "s#test-5.x.cfg#travis-$PLONE_VERSION.x.cfg#" buildout.cfg
  - python bootstrap.py --buildout-version=2.9.4 --setuptools-version=33.1.1
  - bin/buildout annotate
  - bin/buildout -N -q versions:setuptools= versions:zc.buildout=
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage --output-dir=parts/test/coverage
  - pip install -q coveralls
  - coveralls
