language: python
sudo: false
python: 2.7
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
cache:
  pip: true
  directories:
    - eggs
    - downloads
install:
  - sed -ie "s#test-5.x.cfg#travis-$PLONE_VERSION.x.cfg#" buildout.cfg
  - python bootstrap.py
  - bin/buildout annotate
  - bin/buildout -N -q
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: 
  - bin/coverage run bin/test
  - bin/code-analysis
after_success:
  - pip install -q coveralls python-coveralls==2.5.0 coverage==3.7.1
  - coveralls
